version: "3"

services:
  navcoind:
    build:
        context: .
        args:
            USER_ID: 1000
            GROUP_ID: 1000
    ports:
      - 44440:44440
      - 44444:44444
      - 44445:44445
    expose:
      - "44440"
      - "44444"
      - "44445"
    command: /bin/bash ./navcoind_testnet.sh
